# Linting workflow
name: lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::lintr
            any::styler
          needs: check

      - name: Lint
        run: |
          # Run styler to check code style
          styler::style_pkg(dry = "on")
          
          # Run lintr to check for common issues
          lintr::lint_package()
        shell: Rscript {0}

      - name: Check for style issues
        run: |
          # Check if styler would make changes
          if ! styler::style_pkg(dry = "on") == ""; then
            echo "Code style issues found. Please run styler::style_pkg() to fix."
            exit 1
          fi
        shell: Rscript {0}